Feature/2 message retention
seliumlabs/selium pull request #189
Opened 2024-04-18 06:19 UTC by adenh93

2024-04-19 00:14 UTC, petehayes102 requested changes
Looks awesome mate! Just some petty stuff. Great job!!

2024-04-19 00:14 UTC, petehayes102 commented on protocol/src/frame.rs
> +    pub fn unwrap_batch_size(&self) -> u32 {
I get that these don't have to take ownership, but maybe they should be called something else, or take ownership for symmetry?

2024-04-19 00:14 UTC, petehayes102 commented on protocol/src/frame.rs
> +    pub fn unwrap_retention_policy(&self) -> u64 {
I get that these don't have to take ownership, but maybe they should be called something else, or take ownership for symmetry?

2024-04-19 00:14 UTC, petehayes102 commented on tests/tests/streams/pub_sub.rs
These should be reworked before we merge. AFAIK your changes to the topic `Future`s have no automated test coverage without these?

2024-04-22 06:11 UTC, adenh93 commented on client/src/constants.rs
> +pub const RETENTION_POLICY_DEFAULT: u64 = 1000 * 60 * 60 * 24;
Resolving this conversation, as we will be implementing support for streaming with and without retention in the near future.

2024-04-22 06:12 UTC, adenh93 commented on log/Cargo.toml
> +# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
Whoops! 🤣

2024-04-22 06:13 UTC, adenh93 commented on log/src/message/mod.rs
> +    _crc: u32,
I've added a TODO for now. The CRC will be implemented once we have replication. For now, it's generated for the messages in preparation for the feature.

2024-04-22 06:13 UTC, adenh93 commented on tests/tests/streams/pub_sub.rs
Fixed the tests now! 👍

2024-04-23 23:20 UTC, petehayes102 approved these changes

2024-04-24 05:20 UTC, petehayes102 approved these changes

2024-04-24 05:20 UTC, merged